trigger:
- none

pool: testingpool

variables:
  secret: '$(azure-fed)'

parameters:
- name: runInit
  displayName: "terraform init"
  type: boolean
  default: false

- name: runplan
  displayName: "terraform plan"
  type: boolean
  default: false

- name: runapply
  displayName: "terraform apply"
  type: boolean
  default: false

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- ${{ if eq(parameters.runInit, true) }}:
  - task: TerraformTask@5
    displayName: Terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: '$(secret)'
      backendAzureRmStorageAccountName: 'storage552'
      backendAzureRmContainerName: 'cont1'
      backendAzureRmKey: 'terraform.tfstate'

- ${{ if eq(parameters.runplan, true) }}:
  - task: TerraformTask@5
    displayName: Terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: '$(secret)'

- ${{ if eq(parameters.runapply, true) }}:
  - task: TerraformTask@5
    displayName: Terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: '$(secret)'
