
trigger:
- none

pool: testingpool
variables:
  secret: '$(azure-fed)'
  
parameters:
- name: runInit
  displayName: "terrafom init"
  type: boolean
  default: false

- name: runplan
  displayName: "terraform plan"
  type: boolean
  default: false

- name: runapply
  displayName: "terraform apply"
  type: boolean
  default: false

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'secret'
    backendAzureRmStorageAccountName: 'storage5'
    backendAzureRmContainerName: 'cont1'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'secret'
- task: TerraformTask@5
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'secret'